## ===-- llvm-c/TargetMachine.h - Target Machine Library C Interface - C++ -*-=*\
## |*                                                                            *|
## |*                     The LLVM Compiler Infrastructure                       *|
## |*                                                                            *|
## |* This file is distributed under the University of Illinois Open Source      *|
## |* License. See LICENSE.TXT for details.                                      *|
## |*                                                                            *|
## |*===----------------------------------------------------------------------===*|
## |*                                                                            *|
## |* This header declares the C interface to the Target and TargetMachine       *|
## |* classes, which can be used to generate assembly or object files.           *|
## |*                                                                            *|
## |* Many exotic languages can interoperate with C code but have a harder time  *|
## |* with C++ due to name mangling. So in addition to C, this interface enables *|
## |* tools written in such languages.                                           *|
## |*                                                                            *|
## \*===----------------------------------------------------------------------===

type
  TargetMachineRef* = ptr OpaqueTargetMachine
  TargetRef* = ptr target
  CodeGenOptLevel* {.size: sizeof(cint).} = enum
    CodeGenLevelNone, CodeGenLevelLess, CodeGenLevelDefault, CodeGenLevelAggressive
  RelocMode* {.size: sizeof(cint).} = enum
    RelocDefault, RelocStatic, RelocPIC, RelocDynamicNoPic
  CodeModel* {.size: sizeof(cint).} = enum
    CodeModelDefault, CodeModelJITDefault, CodeModelSmall, CodeModelKernel,
    CodeModelMedium, CodeModelLarge
  CodeGenFileType* {.size: sizeof(cint).} = enum
    AssemblyFile, ObjectFile





## * Returns the first llvm::Target in the registered targets list.

proc GetFirstTarget*(): TargetRef {.llvmc.}
## * Returns the next llvm::Target given a previous one (or null if there's none)

proc GetNextTarget*(t: TargetRef): TargetRef {.llvmc.}
## ===-- Target ------------------------------------------------------------===
## * Finds the target corresponding to the given name and stores it in \p T.
##   Returns 0 on success.

proc GetTargetFromName*(name: cstring): TargetRef {.llvmc.}
## * Finds the target corresponding to the given triple and stores it in \p T.
##   Returns 0 on success. Optionally returns any error in ErrorMessage.
##   Use LLVMDisposeMessage to dispose the message.

proc GetTargetFromTriple*(triple: cstring; t: ptr TargetRef;
                         errorMessage: cstringArray): Bool {.llvmc.}
## * Returns the name of a target. See llvm::Target::getName

proc GetTargetName*(t: TargetRef): cstring {.llvmc.}
## * Returns the description  of a target. See llvm::Target::getDescription

proc GetTargetDescription*(t: TargetRef): cstring {.llvmc.}
## * Returns if the target has a JIT

proc TargetHasJIT*(t: TargetRef): Bool {.llvmc.}
## * Returns if the target has a TargetMachine associated

proc TargetHasTargetMachine*(t: TargetRef): Bool {.llvmc.}
## * Returns if the target as an ASM backend (required for emitting output)

proc TargetHasAsmBackend*(t: TargetRef): Bool {.llvmc.}
## ===-- Target Machine ----------------------------------------------------===
## * Creates a new llvm::TargetMachine. See llvm::Target::createTargetMachine

proc CreateTargetMachine*(t: TargetRef; triple: cstring; cpu: cstring;
                         features: cstring; level: CodeGenOptLevel;
                         reloc: RelocMode; codeModel: CodeModel): TargetMachineRef {.llvmc.}
## * Dispose the LLVMTargetMachineRef instance generated by
##   LLVMCreateTargetMachine.

proc DisposeTargetMachine*(t: TargetMachineRef) {.llvmc.}
## * Returns the Target used in a TargetMachine

proc GetTargetMachineTarget*(t: TargetMachineRef): TargetRef {.llvmc.}
## * Returns the triple used creating this target machine. See
##   llvm::TargetMachine::getTriple. The result needs to be disposed with
##   LLVMDisposeMessage.

proc GetTargetMachineTriple*(t: TargetMachineRef): cstring {.llvmc.}
## * Returns the cpu used creating this target machine. See
##   llvm::TargetMachine::getCPU. The result needs to be disposed with
##   LLVMDisposeMessage.

proc GetTargetMachineCPU*(t: TargetMachineRef): cstring {.llvmc.}
## * Returns the feature string used creating this target machine. See
##   llvm::TargetMachine::getFeatureString. The result needs to be disposed with
##   LLVMDisposeMessage.

proc GetTargetMachineFeatureString*(t: TargetMachineRef): cstring {.llvmc.}
## * Create a DataLayout based on the targetMachine.

proc CreateTargetDataLayout*(t: TargetMachineRef): TargetDataRef {.llvmc.}
## * Set the target machine's ASM verbosity.

proc SetTargetMachineAsmVerbosity*(t: TargetMachineRef; verboseAsm: Bool) {.llvmc.}
## * Emits an asm or object file for the given module to the filename. This
##   wraps several c++ only classes (among them a file stream). Returns any
##   error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.

proc TargetMachineEmitToFile*(t: TargetMachineRef; m: ModuleRef; filename: cstring;
                             codegen: CodeGenFileType; errorMessage: cstringArray): Bool {.llvmc.}
## * Compile the LLVM IR stored in \p M and store the result in \p OutMemBuf.

proc TargetMachineEmitToMemoryBuffer*(t: TargetMachineRef; m: ModuleRef;
                                     codegen: CodeGenFileType;
                                     errorMessage: cstringArray;
                                     outMemBuf: ptr MemoryBufferRef): Bool {.llvmc.}
## ===-- Triple ------------------------------------------------------------===
## * Get a triple for the host machine as a string. The result needs to be
##   disposed with LLVMDisposeMessage.

proc GetDefaultTargetTriple*(): cstring {.llvmc.}
## * Adds the target-specific analysis passes to the pass manager.

proc AddAnalysisPasses*(t: TargetMachineRef; pm: PassManagerRef) {.llvmc.}